// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user_service.proto

package userpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Picture              string   `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_service_e3c540665cfe7ded, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

type UserLoginRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_service_e3c540665cfe7ded, []int{1}
}
func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (dst *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(dst, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserLoginResponse struct {
	// Whether this is a new user or not.
	New                  bool     `protobuf:"varint,1,opt,name=new,proto3" json:"new,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResponse) Reset()         { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()    {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_service_e3c540665cfe7ded, []int{2}
}
func (m *UserLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResponse.Unmarshal(m, b)
}
func (m *UserLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResponse.Marshal(b, m, deterministic)
}
func (dst *UserLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResponse.Merge(dst, src)
}
func (m *UserLoginResponse) XXX_Size() int {
	return xxx_messageInfo_UserLoginResponse.Size(m)
}
func (m *UserLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResponse proto.InternalMessageInfo

func (m *UserLoginResponse) GetNew() bool {
	if m != nil {
		return m.New
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*UserLoginRequest)(nil), "user.UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "user.UserLoginResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error) {
	out := new(UserLoginResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/UserLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	UserLogin(context.Context, *UserLoginRequest) (*UserLoginResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_UserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserLogin(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserLogin",
			Handler:    _UserService_UserLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/user_service.proto",
}

func init() {
	proto.RegisterFile("proto/user/user_service.proto", fileDescriptor_user_service_e3c540665cfe7ded)
}

var fileDescriptor_user_service_e3c540665cfe7ded = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x5d, 0xb7, 0xae, 0xed, 0xec, 0x65, 0x1d, 0x44, 0x43, 0x51, 0x91, 0x82, 0xe0, 0xa9,
	0x42, 0xbd, 0x7b, 0xf0, 0xac, 0x1e, 0x22, 0x5e, 0xbc, 0x48, 0x5b, 0x46, 0x09, 0xb4, 0x4d, 0x4c,
	0x52, 0xfd, 0xfb, 0x92, 0x89, 0xb6, 0x05, 0x2f, 0x21, 0xef, 0x7b, 0x33, 0xf3, 0x26, 0x81, 0x73,
	0x63, 0xb5, 0xd7, 0x37, 0xa3, 0x23, 0xcb, 0xc7, 0x9b, 0x23, 0xfb, 0xa5, 0x5a, 0x2a, 0x99, 0x63,
	0x12, 0x58, 0x61, 0x20, 0x79, 0x71, 0x64, 0xf1, 0x0c, 0xb2, 0x77, 0x65, 0x9d, 0x7f, 0xaa, 0x7b,
	0x12, 0xab, 0xcb, 0xd5, 0x75, 0x26, 0x67, 0x80, 0x39, 0xa4, 0x5d, 0xfd, 0x6b, 0xee, 0xb3, 0x39,
	0x69, 0x3c, 0x86, 0x03, 0xea, 0x6b, 0xd5, 0x89, 0x35, 0x1b, 0x51, 0xa0, 0x80, 0x43, 0xa3, 0x5a,
	0x3f, 0x5a, 0x12, 0x09, 0xf3, 0x3f, 0x59, 0x54, 0xb0, 0x0b, 0x89, 0x0f, 0xfa, 0x43, 0x0d, 0x92,
	0x3e, 0x47, 0x72, 0x1e, 0x2f, 0x80, 0xb7, 0xe1, 0xe0, 0x6d, 0x05, 0x65, 0x10, 0x65, 0xa8, 0x92,
	0x71, 0xcb, 0x2b, 0x38, 0x5a, 0xf4, 0x38, 0xa3, 0x07, 0x47, 0xb8, 0x83, 0xf5, 0x40, 0xdf, 0xdc,
	0x93, 0xca, 0x70, 0xad, 0x1e, 0x61, 0x1b, 0xca, 0x9e, 0xe3, 0x3b, 0xf1, 0x0e, 0xb2, 0xa9, 0x0b,
	0x4f, 0xe6, 0xa1, 0xcb, 0xe8, 0xfc, 0xf4, 0x1f, 0x8f, 0xe3, 0x8b, 0xbd, 0xfb, 0xf4, 0x75, 0x13,
	0x3c, 0xd3, 0x34, 0x1b, 0xfe, 0xb2, 0xdb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x60, 0x44,
	0xf4, 0x53, 0x01, 0x00, 0x00,
}
