// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plaid/plaid_service.proto

package plaid

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transaction_Type int32

const (
	Transaction_UNRESOLVED Transaction_Type = 0
	Transaction_DIGITAL    Transaction_Type = 1
	Transaction_PLACE      Transaction_Type = 2
	Transaction_SPECIAL    Transaction_Type = 3
)

var Transaction_Type_name = map[int32]string{
	0: "UNRESOLVED",
	1: "DIGITAL",
	2: "PLACE",
	3: "SPECIAL",
}
var Transaction_Type_value = map[string]int32{
	"UNRESOLVED": 0,
	"DIGITAL":    1,
	"PLACE":      2,
	"SPECIAL":    3,
}

func (x Transaction_Type) String() string {
	return proto.EnumName(Transaction_Type_name, int32(x))
}
func (Transaction_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_plaid_service_a5ad981480fec5c4, []int{2, 0}
}

type Transaction_Currency int32

const (
	Transaction_USD Transaction_Currency = 0
	Transaction_CAD Transaction_Currency = 1
)

var Transaction_Currency_name = map[int32]string{
	0: "USD",
	1: "CAD",
}
var Transaction_Currency_value = map[string]int32{
	"USD": 0,
	"CAD": 1,
}

func (x Transaction_Currency) String() string {
	return proto.EnumName(Transaction_Currency_name, int32(x))
}
func (Transaction_Currency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_plaid_service_a5ad981480fec5c4, []int{2, 1}
}

type ExchangeTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeTokenRequest) Reset()         { *m = ExchangeTokenRequest{} }
func (m *ExchangeTokenRequest) String() string { return proto.CompactTextString(m) }
func (*ExchangeTokenRequest) ProtoMessage()    {}
func (*ExchangeTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plaid_service_a5ad981480fec5c4, []int{0}
}
func (m *ExchangeTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeTokenRequest.Unmarshal(m, b)
}
func (m *ExchangeTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeTokenRequest.Marshal(b, m, deterministic)
}
func (dst *ExchangeTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeTokenRequest.Merge(dst, src)
}
func (m *ExchangeTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ExchangeTokenRequest.Size(m)
}
func (m *ExchangeTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeTokenRequest proto.InternalMessageInfo

func (m *ExchangeTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ExchangeTokenResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ItemId               string   `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeTokenResponse) Reset()         { *m = ExchangeTokenResponse{} }
func (m *ExchangeTokenResponse) String() string { return proto.CompactTextString(m) }
func (*ExchangeTokenResponse) ProtoMessage()    {}
func (*ExchangeTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plaid_service_a5ad981480fec5c4, []int{1}
}
func (m *ExchangeTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeTokenResponse.Unmarshal(m, b)
}
func (m *ExchangeTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeTokenResponse.Marshal(b, m, deterministic)
}
func (dst *ExchangeTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeTokenResponse.Merge(dst, src)
}
func (m *ExchangeTokenResponse) XXX_Size() int {
	return xxx_messageInfo_ExchangeTokenResponse.Size(m)
}
func (m *ExchangeTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeTokenResponse proto.InternalMessageInfo

func (m *ExchangeTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ExchangeTokenResponse) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

// https://plaid.com/docs/api/#transactions
type Transaction struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            string                   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Category             []string                 `protobuf:"bytes,3,rep,name=category,proto3" json:"category,omitempty"`
	CategoryId           string                   `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Type                 Transaction_Type         `protobuf:"varint,5,opt,name=type,proto3,enum=plaid.Transaction_Type" json:"type,omitempty"`
	MerchantName         string                   `protobuf:"bytes,6,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	Amount               float64                  `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	CurrencyType         Transaction_Currency     `protobuf:"varint,8,opt,name=currency_type,json=currencyType,proto3,enum=plaid.Transaction_Currency" json:"currency_type,omitempty"`
	Date                 string                   `protobuf:"bytes,9,opt,name=date,proto3" json:"date,omitempty"`
	Location             *Transaction_Location    `protobuf:"bytes,10,opt,name=location,proto3" json:"location,omitempty"`
	PaymentMeta          *Transaction_PaymentMeta `protobuf:"bytes,11,opt,name=payment_meta,json=paymentMeta,proto3" json:"payment_meta,omitempty"`
	Pending              bool                     `protobuf:"varint,12,opt,name=pending,proto3" json:"pending,omitempty"`
	PendingTransactionId string                   `protobuf:"bytes,13,opt,name=pending_transaction_id,json=pendingTransactionId,proto3" json:"pending_transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_plaid_service_a5ad981480fec5c4, []int{2}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Transaction) GetCategory() []string {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Transaction) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *Transaction) GetType() Transaction_Type {
	if m != nil {
		return m.Type
	}
	return Transaction_UNRESOLVED
}

func (m *Transaction) GetMerchantName() string {
	if m != nil {
		return m.MerchantName
	}
	return ""
}

func (m *Transaction) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetCurrencyType() Transaction_Currency {
	if m != nil {
		return m.CurrencyType
	}
	return Transaction_USD
}

func (m *Transaction) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Transaction) GetLocation() *Transaction_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Transaction) GetPaymentMeta() *Transaction_PaymentMeta {
	if m != nil {
		return m.PaymentMeta
	}
	return nil
}

func (m *Transaction) GetPending() bool {
	if m != nil {
		return m.Pending
	}
	return false
}

func (m *Transaction) GetPendingTransactionId() string {
	if m != nil {
		return m.PendingTransactionId
	}
	return ""
}

type Transaction_Location struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Lat                  float64  `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	State                string   `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	StoreNumber          string   `protobuf:"bytes,6,opt,name=store_number,json=storeNumber,proto3" json:"store_number,omitempty"`
	Zip                  string   `protobuf:"bytes,7,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_Location) Reset()         { *m = Transaction_Location{} }
func (m *Transaction_Location) String() string { return proto.CompactTextString(m) }
func (*Transaction_Location) ProtoMessage()    {}
func (*Transaction_Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_plaid_service_a5ad981480fec5c4, []int{2, 0}
}
func (m *Transaction_Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_Location.Unmarshal(m, b)
}
func (m *Transaction_Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_Location.Marshal(b, m, deterministic)
}
func (dst *Transaction_Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_Location.Merge(dst, src)
}
func (m *Transaction_Location) XXX_Size() int {
	return xxx_messageInfo_Transaction_Location.Size(m)
}
func (m *Transaction_Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_Location proto.InternalMessageInfo

func (m *Transaction_Location) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Transaction_Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Transaction_Location) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Transaction_Location) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *Transaction_Location) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Transaction_Location) GetStoreNumber() string {
	if m != nil {
		return m.StoreNumber
	}
	return ""
}

func (m *Transaction_Location) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

type Transaction_PaymentMeta struct {
	ByOrderOf            string   `protobuf:"bytes,1,opt,name=by_order_of,json=byOrderOf,proto3" json:"by_order_of,omitempty"`
	Payee                string   `protobuf:"bytes,2,opt,name=payee,proto3" json:"payee,omitempty"`
	Payer                string   `protobuf:"bytes,3,opt,name=payer,proto3" json:"payer,omitempty"`
	PaymentMethod        string   `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaymentProcessor     string   `protobuf:"bytes,5,opt,name=payment_processor,json=paymentProcessor,proto3" json:"payment_processor,omitempty"`
	Ppdid                string   `protobuf:"bytes,6,opt,name=ppdid,proto3" json:"ppdid,omitempty"`
	Reason               string   `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	ReferenceNumber      string   `protobuf:"bytes,8,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_PaymentMeta) Reset()         { *m = Transaction_PaymentMeta{} }
func (m *Transaction_PaymentMeta) String() string { return proto.CompactTextString(m) }
func (*Transaction_PaymentMeta) ProtoMessage()    {}
func (*Transaction_PaymentMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_plaid_service_a5ad981480fec5c4, []int{2, 1}
}
func (m *Transaction_PaymentMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_PaymentMeta.Unmarshal(m, b)
}
func (m *Transaction_PaymentMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_PaymentMeta.Marshal(b, m, deterministic)
}
func (dst *Transaction_PaymentMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_PaymentMeta.Merge(dst, src)
}
func (m *Transaction_PaymentMeta) XXX_Size() int {
	return xxx_messageInfo_Transaction_PaymentMeta.Size(m)
}
func (m *Transaction_PaymentMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_PaymentMeta.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_PaymentMeta proto.InternalMessageInfo

func (m *Transaction_PaymentMeta) GetByOrderOf() string {
	if m != nil {
		return m.ByOrderOf
	}
	return ""
}

func (m *Transaction_PaymentMeta) GetPayee() string {
	if m != nil {
		return m.Payee
	}
	return ""
}

func (m *Transaction_PaymentMeta) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

func (m *Transaction_PaymentMeta) GetPaymentMethod() string {
	if m != nil {
		return m.PaymentMethod
	}
	return ""
}

func (m *Transaction_PaymentMeta) GetPaymentProcessor() string {
	if m != nil {
		return m.PaymentProcessor
	}
	return ""
}

func (m *Transaction_PaymentMeta) GetPpdid() string {
	if m != nil {
		return m.Ppdid
	}
	return ""
}

func (m *Transaction_PaymentMeta) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Transaction_PaymentMeta) GetReferenceNumber() string {
	if m != nil {
		return m.ReferenceNumber
	}
	return ""
}

type GetTransactionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionsRequest) Reset()         { *m = GetTransactionsRequest{} }
func (m *GetTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionsRequest) ProtoMessage()    {}
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plaid_service_a5ad981480fec5c4, []int{3}
}
func (m *GetTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionsRequest.Unmarshal(m, b)
}
func (m *GetTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionsRequest.Marshal(b, m, deterministic)
}
func (dst *GetTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionsRequest.Merge(dst, src)
}
func (m *GetTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionsRequest.Size(m)
}
func (m *GetTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionsRequest proto.InternalMessageInfo

type GetTransactionsResponse struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTransactionsResponse) Reset()         { *m = GetTransactionsResponse{} }
func (m *GetTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionsResponse) ProtoMessage()    {}
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plaid_service_a5ad981480fec5c4, []int{4}
}
func (m *GetTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionsResponse.Unmarshal(m, b)
}
func (m *GetTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionsResponse.Marshal(b, m, deterministic)
}
func (dst *GetTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionsResponse.Merge(dst, src)
}
func (m *GetTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionsResponse.Size(m)
}
func (m *GetTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionsResponse proto.InternalMessageInfo

func (m *GetTransactionsResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*ExchangeTokenRequest)(nil), "plaid.ExchangeTokenRequest")
	proto.RegisterType((*ExchangeTokenResponse)(nil), "plaid.ExchangeTokenResponse")
	proto.RegisterType((*Transaction)(nil), "plaid.Transaction")
	proto.RegisterType((*Transaction_Location)(nil), "plaid.Transaction.Location")
	proto.RegisterType((*Transaction_PaymentMeta)(nil), "plaid.Transaction.PaymentMeta")
	proto.RegisterType((*GetTransactionsRequest)(nil), "plaid.GetTransactionsRequest")
	proto.RegisterType((*GetTransactionsResponse)(nil), "plaid.GetTransactionsResponse")
	proto.RegisterEnum("plaid.Transaction_Type", Transaction_Type_name, Transaction_Type_value)
	proto.RegisterEnum("plaid.Transaction_Currency", Transaction_Currency_name, Transaction_Currency_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlaidClient is the client API for Plaid service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlaidClient interface {
	ExchangeToken(ctx context.Context, in *ExchangeTokenRequest, opts ...grpc.CallOption) (*ExchangeTokenResponse, error)
	GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error)
}

type plaidClient struct {
	cc *grpc.ClientConn
}

func NewPlaidClient(cc *grpc.ClientConn) PlaidClient {
	return &plaidClient{cc}
}

func (c *plaidClient) ExchangeToken(ctx context.Context, in *ExchangeTokenRequest, opts ...grpc.CallOption) (*ExchangeTokenResponse, error) {
	out := new(ExchangeTokenResponse)
	err := c.cc.Invoke(ctx, "/plaid.Plaid/ExchangeToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plaidClient) GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error) {
	out := new(GetTransactionsResponse)
	err := c.cc.Invoke(ctx, "/plaid.Plaid/GetTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaidServer is the server API for Plaid service.
type PlaidServer interface {
	ExchangeToken(context.Context, *ExchangeTokenRequest) (*ExchangeTokenResponse, error)
	GetTransactions(context.Context, *GetTransactionsRequest) (*GetTransactionsResponse, error)
}

func RegisterPlaidServer(s *grpc.Server, srv PlaidServer) {
	s.RegisterService(&_Plaid_serviceDesc, srv)
}

func _Plaid_ExchangeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaidServer).ExchangeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plaid.Plaid/ExchangeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaidServer).ExchangeToken(ctx, req.(*ExchangeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plaid_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaidServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plaid.Plaid/GetTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaidServer).GetTransactions(ctx, req.(*GetTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plaid_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plaid.Plaid",
	HandlerType: (*PlaidServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExchangeToken",
			Handler:    _Plaid_ExchangeToken_Handler,
		},
		{
			MethodName: "GetTransactions",
			Handler:    _Plaid_GetTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plaid/plaid_service.proto",
}

func init() {
	proto.RegisterFile("plaid/plaid_service.proto", fileDescriptor_plaid_service_a5ad981480fec5c4)
}

var fileDescriptor_plaid_service_a5ad981480fec5c4 = []byte{
	// 752 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdd, 0x6e, 0xe2, 0x46,
	0x14, 0xae, 0x31, 0x3f, 0xe6, 0x18, 0x88, 0x3b, 0x4a, 0x13, 0x97, 0x26, 0x29, 0xa5, 0xaa, 0x44,
	0xd5, 0x8a, 0x4a, 0x69, 0xd5, 0x5e, 0xf4, 0xa6, 0x88, 0xa0, 0x88, 0x8a, 0x4d, 0x58, 0x43, 0xf6,
	0xd6, 0x1a, 0xec, 0x93, 0xc4, 0xda, 0xd8, 0xe3, 0x1d, 0x0f, 0xab, 0xf5, 0x3e, 0xc0, 0xbe, 0xc0,
	0x3e, 0xc3, 0x6a, 0x5f, 0x73, 0x35, 0xe3, 0x31, 0x90, 0x84, 0xbd, 0xb1, 0xce, 0xf7, 0x9d, 0xdf,
	0x39, 0xf3, 0x79, 0xe0, 0xfb, 0xf4, 0x81, 0x46, 0xe1, 0x1f, 0xea, 0xeb, 0x67, 0xc8, 0xdf, 0x46,
	0x01, 0x0e, 0x53, 0xce, 0x04, 0x23, 0x35, 0x45, 0xf6, 0x7f, 0x87, 0xc3, 0xc9, 0xbb, 0xe0, 0x9e,
	0x26, 0x77, 0xb8, 0x64, 0xaf, 0x31, 0xf1, 0xf0, 0xcd, 0x1a, 0x33, 0x41, 0x0e, 0xa1, 0x26, 0x24,
	0x76, 0x8d, 0x9e, 0x31, 0x68, 0x7a, 0x05, 0xe8, 0x2f, 0xe0, 0xbb, 0x27, 0xd1, 0x59, 0xca, 0x92,
	0x0c, 0xc9, 0x4f, 0xd0, 0xa2, 0x41, 0x80, 0x59, 0xe6, 0xef, 0x66, 0xd9, 0x05, 0xa7, 0x42, 0xc9,
	0x31, 0x34, 0x22, 0x81, 0xb1, 0x1f, 0x85, 0x6e, 0x45, 0x79, 0xeb, 0x12, 0x4e, 0xc3, 0xfe, 0x47,
	0x0b, 0xec, 0x25, 0xa7, 0x49, 0x46, 0x03, 0x11, 0xb1, 0x84, 0x74, 0xa0, 0x12, 0x85, 0xba, 0x42,
	0x25, 0x0a, 0xc9, 0x29, 0x00, 0x0d, 0x02, 0xb6, 0x4e, 0xc4, 0x36, 0xb7, 0xa9, 0x99, 0x69, 0x48,
	0xba, 0x60, 0x05, 0x54, 0xe0, 0x1d, 0xe3, 0xb9, 0x6b, 0xf6, 0xcc, 0x41, 0xd3, 0xdb, 0x60, 0xf2,
	0x23, 0xd8, 0xa5, 0x2d, 0x73, 0xab, 0x2a, 0x17, 0x4a, 0x6a, 0x1a, 0x92, 0xdf, 0xa0, 0x2a, 0xf2,
	0x14, 0xdd, 0x5a, 0xcf, 0x18, 0x74, 0xce, 0x8f, 0x87, 0x6a, 0x29, 0xc3, 0x9d, 0x69, 0x86, 0xcb,
	0x3c, 0x45, 0x4f, 0x05, 0x91, 0x9f, 0xa1, 0x1d, 0x23, 0x97, 0xc7, 0x17, 0x7e, 0x42, 0x63, 0x74,
	0xeb, 0xaa, 0x5e, 0xab, 0x24, 0xaf, 0x68, 0x8c, 0xe4, 0x08, 0xea, 0x34, 0x96, 0xa3, 0xb9, 0x8d,
	0x9e, 0x31, 0x30, 0x3c, 0x8d, 0xc8, 0x7f, 0xd0, 0x0e, 0xd6, 0x9c, 0x63, 0x12, 0xe4, 0xbe, 0x6a,
	0x69, 0xa9, 0x96, 0x3f, 0xec, 0x69, 0x39, 0xd6, 0x71, 0x5e, 0xab, 0xcc, 0x90, 0x43, 0x10, 0x02,
	0xd5, 0x90, 0x0a, 0x74, 0x9b, 0xaa, 0xab, 0xb2, 0xc9, 0x3f, 0x60, 0x3d, 0xb0, 0x80, 0xca, 0x34,
	0x17, 0x7a, 0xc6, 0xc0, 0xde, 0x5b, 0x70, 0xa6, 0x43, 0xbc, 0x4d, 0x30, 0x19, 0x41, 0x2b, 0xa5,
	0x79, 0x8c, 0x89, 0xf0, 0x63, 0x14, 0xd4, 0xb5, 0x55, 0xf2, 0xd9, 0x9e, 0xe4, 0x79, 0x11, 0xf6,
	0x02, 0x05, 0xf5, 0xec, 0x74, 0x0b, 0x88, 0x0b, 0x8d, 0x14, 0x93, 0x30, 0x4a, 0xee, 0xdc, 0x56,
	0xcf, 0x18, 0x58, 0x5e, 0x09, 0xc9, 0x5f, 0x70, 0xa4, 0x4d, 0x5f, 0x6c, 0x2b, 0xc9, 0x1b, 0x68,
	0xab, 0xd9, 0x0f, 0xb5, 0x77, 0xa7, 0xcd, 0x34, 0xec, 0x7e, 0x36, 0xc0, 0x2a, 0x27, 0x95, 0xc5,
	0x69, 0x18, 0x72, 0xcc, 0x32, 0xad, 0x84, 0x12, 0xca, 0x35, 0x04, 0x91, 0xc8, 0xb5, 0x10, 0x94,
	0x4d, 0x1c, 0x30, 0x1f, 0xa8, 0x70, 0x4d, 0xb5, 0x71, 0x69, 0x2a, 0x86, 0x25, 0xea, 0xc6, 0x25,
	0xc3, 0x12, 0xa9, 0xe8, 0x4c, 0xc8, 0xfd, 0xd5, 0x0a, 0x45, 0x2b, 0x20, 0x85, 0x9b, 0x09, 0xc6,
	0xd1, 0x4f, 0xd6, 0xf1, 0x0a, 0xb9, 0xbe, 0x52, 0x5b, 0x71, 0x57, 0x8a, 0x92, 0xa5, 0xde, 0x47,
	0xa9, 0xba, 0xce, 0xa6, 0x27, 0xcd, 0xee, 0x87, 0x0a, 0xd8, 0x3b, 0x6b, 0x21, 0x67, 0x60, 0xaf,
	0x72, 0x9f, 0xf1, 0x10, 0xb9, 0xcf, 0x6e, 0xf5, 0xc0, 0xcd, 0x55, 0x7e, 0x2d, 0x99, 0xeb, 0x5b,
	0xd9, 0x3a, 0xa5, 0x39, 0xa2, 0x9e, 0xb9, 0x00, 0x25, 0xcb, 0xd5, 0xd8, 0x9a, 0xe5, 0xe4, 0x17,
	0xe8, 0xec, 0x5c, 0xcc, 0x3d, 0x2b, 0x55, 0xdb, 0xde, 0xae, 0xfe, 0x9e, 0x49, 0xe1, 0x7e, 0x5b,
	0x86, 0xa5, 0x9c, 0xc9, 0xbf, 0x8c, 0x71, 0x7d, 0x32, 0x47, 0x3b, 0xe6, 0x25, 0xaf, 0x3a, 0xa5,
	0x61, 0x14, 0xea, 0xd3, 0x15, 0x40, 0x2a, 0x95, 0x23, 0xcd, 0x58, 0xa2, 0x8f, 0xa6, 0x11, 0xf9,
	0x15, 0x1c, 0x8e, 0xb7, 0x28, 0x85, 0xb7, 0x59, 0x8b, 0xa5, 0x22, 0x0e, 0x36, 0x7c, 0xb1, 0x9a,
	0xfe, 0xbf, 0x50, 0x55, 0xd2, 0xec, 0x00, 0xdc, 0x5c, 0x79, 0x93, 0xc5, 0xf5, 0xec, 0xd5, 0xe4,
	0xc2, 0xf9, 0x86, 0xd8, 0xd0, 0xb8, 0x98, 0x5e, 0x4e, 0x97, 0xa3, 0x99, 0x63, 0x90, 0x26, 0xd4,
	0xe6, 0xb3, 0xd1, 0x78, 0xe2, 0x54, 0x24, 0xbf, 0x98, 0x4f, 0xc6, 0xd3, 0xd1, 0xcc, 0x31, 0xfb,
	0x27, 0x60, 0x95, 0x4a, 0x27, 0x0d, 0x30, 0x6f, 0x16, 0x32, 0xb3, 0x01, 0xe6, 0x78, 0x74, 0xe1,
	0x18, 0x7d, 0x17, 0x8e, 0x2e, 0x51, 0xec, 0x28, 0x24, 0xd3, 0x4f, 0x53, 0xff, 0x25, 0x1c, 0x3f,
	0xf3, 0xe8, 0x67, 0xe8, 0x6f, 0x68, 0xed, 0x08, 0x4e, 0x4a, 0xc7, 0x1c, 0xd8, 0xe7, 0xe4, 0xb9,
	0xaa, 0xbd, 0x47, 0x71, 0xe7, 0x9f, 0x0c, 0xa8, 0xcd, 0x65, 0x0c, 0xf9, 0x1f, 0xda, 0x8f, 0x5e,
	0x38, 0x52, 0xfe, 0x4f, 0xfb, 0x5e, 0xc9, 0xee, 0xc9, 0x7e, 0xa7, 0x9e, 0x66, 0x0e, 0x07, 0x4f,
	0x06, 0x25, 0xa7, 0x3a, 0x61, 0xff, 0xd1, 0xba, 0x67, 0x5f, 0x73, 0x17, 0x15, 0x57, 0x75, 0xf5,
	0x76, 0xff, 0xf9, 0x25, 0x00, 0x00, 0xff, 0xff, 0x65, 0x4b, 0x9b, 0x97, 0xd8, 0x05, 0x00, 0x00,
}
